### ISSUE TITLE
unnecessary computation in rotation_from_matrix

### ISSUE THREAD

**Issue by christian-rauch** [cgohlke/transformations#3]
In the current implementation of `rotation_from_matrix`, the eignevectors are computed twice. For the first eigenvectors, the rotation matrix is transposed, which is not required when only the real eigenvector is looked for. I.e. `np.linalg.eig(R)[1]` will be identical to `np.linalg.eig(R.T)[1]` for the real eigenvector with size 1. The second eigenvector is used to get the translation part. For a proper transformation matrix, this should be equal to `R[3,:3]`.

Is there a reason why these values are computed this way?

I would suggest computing the angle and the axis using the trace of R as described in http://scipp.ucsc.edu/~haber/ph216/rotation_12.pdf eq. 22 (angle) and eq. 27 (axis).

**Comment by cgohlke** [comment]
Thank you. I think (not sure) the algorithm comes from one of the Graphics Gems chapters. Please note that this package is no longer being developed and efforts are better spent contributing to actively developed modules:

https://github.com/cgohlke/transformations/blob/deb1a195dab70f0f36365a104f9b70505e37b473/transformations/transformations.py#L65-L77

**Comment by christian-rauch** [comment]
In this case, updating the implementation does not make sense. The `transforms3d` looks like the successor of this library and I will probably use that library in future.

You may want to [archive your repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) in order to make it read-only and communicate that this is not further developed.
