### ISSUE TITLE
transformations crashes with numpy error when installed via requirements.txt

### ISSUE THREAD

**Issue by kgreenek** [cgohlke/transformations#4]
When installing the transformations library with an older version of numpy, it crashes with the following error:

```
Traceback (most recent call last):
[redacted]
  File "[redacted]", line 10, in <module>
    import transformations
  File "[redacted]/transformations/__init__.py", line 4, in <module>
    from .transformations import __doc__, __version__  # noqa
  File "[redacted]/transformations/transformations.py", line 1930, in <module>
    _import_module('_transformations', __package__)
  File "[redacted]/transformations/transformations.py", line 1913, in _import_module
    module = import_module('.' + name, package=package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

It works if I first install numpy by running `pip install numpy==1.21.5`, and then I install transformations by running `pip install transformations==2021.6.6`.

However, if I put the same versions of numpy and transformations together in a requirements.txt file and install them with `pip install -r requirements.txt`, then any code that imports transformations will crash with the error above.

I believe this has to do with how the numpy headers are found in the transformations setup.py file, but I am not sure.

When reproducing this, it is important that you do not have numpy previously installed anywhere, and you do not have a pre-built transformations wheel in the pip cache. I ran in a docker container to ensure I had a totally clean cache and nothing system-installed.

**Comment by cgohlke** [comment]
That's a general limitation of setuptools scripts.

**Comment by kgreenek** [comment]
Oh I see. Thank you! I learned something today.

For my personal learning, do you know of a way to handle this situation without requiring the dependencies to be pre-installed outside of pip / requirements.txt?

Here is my use-case:
I am deploying this with bazel along with [rules_python](https://github.com/bazelbuild/rules_python). The build environment is very strict, and it is not be possible to rely on system-installed dependencies. It also is not possible with bazel to do the pip install in multiple phases as I described in the description as a work-around.

I switched to using scipy, and it seems to be working the way I expected. I'm curious though for my own learning how to handle C extensions that depend on other pip-installed C libraries.
